layout_spectrum: 0.6358989784366792
typography_spectrum: 0.07230909197010321
color:
  brandStrength: 0.5091432874611957
  lightness: 0.24306003913283347
  saturation: 0.5442322933660028
  rhythmicContrast: 0.16470474489392842
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
content_rating:
  adult: false
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4cfcbf1c-4d33-412d-8c0f-110271997ef9.jpg
name: bierhausinstiut
navigation:
  - name: ABOUT
    id: 5570eb70-bfdf-44e4-a5d2-1125b3f7893e
    type: content
  - name: BLOG
    id: 7a3caf6b-c442-4478-8366-ca4fc6021c44
    type: content
  - name: COURSES
    id: 9774af8f-f0c7-4913-938d-af7bc0868ddd
    type: content
  - name: RESOURCE LIBRARY
    id: db92eb0b-70df-4bc3-81df-c89373a44c25
    type: content
  - name: CONTACT
    id: 0fd12b09-cb16-4ce3-a000-3b30ec01d8c0
    type: content
  - name: COMMUNITY
    id: 66e77b75-68fa-482e-aa87-30ad6953448b
    type: content
  - name: MAGAZINE
    id: bf1607b9-e89d-4bda-a93f-d286e39ff7c5
    type: content
  - name: COURSES
    id: 5889d0a0-24cf-4d50-8b19-a6a902984b0e
    type: content
  - name: SHOP
    id: ffdb66f4-ad1d-43e1-b3e3-aae92d2303af
    type: content
  - name: TERMS and CONDITIONS
    id: a3ddeb25-96e0-47f8-82c6-6ff9cdb3964c
    type: content
  - name: MAGAZINE
    id: 3ee580da-ac34-427e-9f2c-3e5990314f8c
    type: content
  - name: RESOURCE LIBRARY
    id: e730142c-f1c2-4b7d-9d38-41515df37cf9
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/be903251-211b-4db5-99dd-3d7ab9fe4249.jpg
title: ' A CAREER IN CRAFT BEER'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F0x9Yifuohlw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D0x9Yifuohlw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F0x9Yifuohlw%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Experience King
          url: 'https://www.youtube.com/channel/UCbleMjydpyl-_yXBzwoJFkA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - duration
        - truck
        - views
        - food
        - beer
        - festival
        - unibroue
        - wheels
        - '2015'
        - parque
      description: Uploaded by Experience King on 2015-07-21.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=0x9Yifuohlw&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=0x9Yifuohlw&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=0x9Yifuohlw&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=0x9Yifuohlw&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=0x9Yifuohlw&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=0x9Yifuohlw'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=0x9Yifuohlw
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=0x9Yifuohlw
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/0x9Yifuohlw'
      title: King City Craft Beer & Food Truck Festival 2015
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fae4bb80-87a0-4198-a385-70cba4e5423c.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fae4bb80-87a0-4198-a385-70cba4e5423c.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a13b2139-3627-4252-a685-89d59d118e28.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a13b2139-3627-4252-a685-89d59d118e28.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ec0816a-7ce7-47d6-8761-8c387f6b85da.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ec0816a-7ce7-47d6-8761-8c387f6b85da.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Empowering Craft Beer Enthusiasts With Self Guided Courses
purpose:
  - type: contact
    url: 'tel:1-416-550-0765'
    label: FREE - 6 Day Email Mini - Course
  - type: contact
    url: 'mailto:hi@bierhausinstitut.com'
    label: Contact Us
