typography_spectrum: 0.811314307599891
content_rating:
  adult: false
color:
  brandStrength: 0.41325234844994796
  lightness: 0.17329866340051933
  saturation: 0.6872746076851641
  rhythmicContrast: 0.5944228162865458
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
layout_spectrum: 0.07886193805116018
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4cfcbf1c-4d33-412d-8c0f-110271997ef9.jpg
name: bierhausinstiut
navigation:
  - name: ABOUT
    id: 5570eb70-bfdf-44e4-a5d2-1125b3f7893e
    type: content
  - name: BLOG
    id: 7a3caf6b-c442-4478-8366-ca4fc6021c44
    type: content
  - name: COURSES
    id: 9774af8f-f0c7-4913-938d-af7bc0868ddd
    type: content
  - name: RESOURCE LIBRARY
    id: db92eb0b-70df-4bc3-81df-c89373a44c25
    type: content
  - name: CONTACT
    id: 0fd12b09-cb16-4ce3-a000-3b30ec01d8c0
    type: content
  - name: COMMUNITY
    id: 66e77b75-68fa-482e-aa87-30ad6953448b
    type: content
  - name: MAGAZINE
    id: bf1607b9-e89d-4bda-a93f-d286e39ff7c5
    type: content
  - name: COURSES
    id: 5889d0a0-24cf-4d50-8b19-a6a902984b0e
    type: content
  - name: SHOP
    id: ffdb66f4-ad1d-43e1-b3e3-aae92d2303af
    type: content
  - name: TERMS and CONDITIONS
    id: a3ddeb25-96e0-47f8-82c6-6ff9cdb3964c
    type: content
  - name: MAGAZINE
    id: 3ee580da-ac34-427e-9f2c-3e5990314f8c
    type: content
  - name: RESOURCE LIBRARY
    id: e730142c-f1c2-4b7d-9d38-41515df37cf9
    type: content
favicon: null
title: ' A CAREER IN CRAFT BEER'
content: []
description: Empowering Craft Beer Enthusiasts With Self Guided Courses
purpose:
  - type: contact
    url: 'tel:1-416-550-0765'
    label: FREE 6-Day Email Course
  - type: contact
    url: 'tel:1-416-550-0765'
    label: FREE 6-Day Email Course
